spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sns_db?useSSL=false&serverTimezone=Asia/Seoul
    username: sns_user
    password: jhj!236884400
  jpa:
    hibernate:
      ddl-auto: update        # ?? ?? ???? ??? ??/??, ???? validate ??
    show-sql: true            # ?? ?? ??
    properties:
      hibernate:
        format_sql: true      # ?? ???
    database-platform: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8081
